### ISSUE TITLE
README

### ISSUE THREAD

**Issue by Amirk390** [FACN3/al-Tarikh#1]
Create a readme file

**Comment by Amirk390** [comment]
Schema Diagram:

![schema](https://user-images.githubusercontent.com/24490876/33606894-c51ec648-d9c7-11e7-9536-1372dd7b81d4.jpg)

**Comment by Amirk390** [comment]
***TEMPORARY*** Architecture Design

![photo 05-12-2017 12 52 50](https://user-images.githubusercontent.com/24490876/33607036-40d99ea2-d9c8-11e7-8c05-46ff99d6fbb7.jpg)

**Comment by Karyum** [comment]
@Amirk390 if this was merged then close this issue
