### ISSUE TITLE
console.logs everywhere...

### ISSUE THREAD

**Issue by MynahMarie** [FACN3/al-Tarikh#30]
Too many console logs!! 

https://github.com/FACN3/al-Tarikh/blob/master/src/handler.js#L21
https://github.com/FACN3/al-Tarikh/blob/master/src/handler.js#L32
https://github.com/FACN3/al-Tarikh/blob/master/src/handler.js#L48

**Comment by MarlenAw** [comment]
@MynahMarie Done :)
