### ISSUE TITLE
Environment variable not ignored

### ISSUE THREAD

**Issue by Karyum** [FACN3/al-Tarikh#34]
we introduced config.env should be ignored in the .gitignore file why is it pushed to github ????!!!!!!

if it's on github ( and github is open for everyone ) then people can just come take your database url either delete everyhing in it or crash it or even fill it up with random shizz

# Never ever push your enviroment variables

**Comment by MarlenAw** [comment]
@Karyum you need to chillax bro!!!!!!!!!!!
You don't actually have access to our database because its stored locally. 
We know that and we added it to .gitignore file..but for some reason it got pushed to github.
