### ISSUE TITLE
strange error

### ISSUE THREAD

**Issue by MynahMarie** [FACN3/al-Tarikh#39]
<img width="1029" alt="screenshot 2017-12-07 10 36 51" src="https://user-images.githubusercontent.com/24983802/33705938-f578b8b6-db3a-11e7-808a-fe6908d70056.png">

**Comment by MynahMarie** [comment]
Never mind I just realized it's because I'm not authenticated in your database ;)

**Comment by MynahMarie** [comment]
But the config.env shouldn't be on github... ;)

**Comment by hoslack** [comment]
We get such issues a lot. It's good that you corrected you authentication. Please close the issue. @MynahMarie
